Sai999 python kinesis
aws-samples/serverless-test-samples pull request #106
Opened 2023-04-10 12:53 UTC by meetreks

*Issue #, if available:*

*Description of changes:*

This PR is to cater for unit & integration mock tests involving kinesis-lambda-dynamodb.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2023-04-18 15:34 UTC, wtromano-aws commented
wtromano-aws review in progress.

2023-04-19 14:51 UTC, wtromano-aws requested changes
Overall, I like the approach and the way it is coded, this will be a great example - thank you!
But some issues prevented it from working for me, so I am not able to fully test it either with unit or integration.  Let me know when the issues are addressed as commented, and I will try again.

2023-04-19 14:51 UTC, wtromano-aws commented on python-test-samples/kinesis-lambda-dynamodb/tests/unit/mock_test.py
> +        #check the mocked DynamoDB to see if PK matches to what we passed to the Kinesss Event
Spelling - Kinesis

2023-04-19 14:51 UTC, wtromano-aws commented on python-test-samples/kinesis-lambda-dynamodb/tests/unit/mock_test.py
pylint:

mock_test.py:27:0: C0303: Trailing whitespace (trailing-whitespace)
mock_test.py:28:0: C0303: Trailing whitespace (trailing-whitespace)
mock_test.py:41:0: C0301: Line too long (108/100) (line-too-long)
mock_test.py:49:0: C0303: Trailing whitespace (trailing-whitespace)
mock_test.py:50:0: C0303: Trailing whitespace (trailing-whitespace)
mock_test.py:55:0: C0303: Trailing whitespace (trailing-whitespace)
mock_test.py:72:0: C0303: Trailing whitespace (trailing-whitespace)
mock_test.py:78:0: C0303: Trailing whitespace (trailing-whitespace)
mock_test.py:87:0: C0303: Trailing whitespace (trailing-whitespace)
mock_test.py:91:0: C0303: Trailing whitespace (trailing-whitespace)
mock_test.py:93:0: C0301: Line too long (107/100) (line-too-long)
mock_test.py:94:0: C0303: Trailing whitespace (trailing-whitespace)
mock_test.py:96:0: C0301: Line too long (139/100) (line-too-long)
mock_test.py:1:0: C0114: Missing module docstring (missing-module-docstring)
mock_test.py:14:0: E0401: Unable to import 'moto' (import-error)
mock_test.py:62:13: W1514: Using open without explicitly specifying an encoding (unspecified-encoding)
mock_test.py:62:43: C0103: Variable name "fp" doesn't conform to snake_case naming style (invalid-name)
mock_test.py:73:17: W1514: Using open without explicitly specifying an encoding (unspecified-encoding)
mock_test.py:73:61: C0103: Variable name "f" doesn't conform to snake_case naming style (invalid-name)
mock_test.py:66:4: R1710: Either all return statements in a function should return an expression, or none of them should. (inconsistent-return-statements)
mock_test.py:89:8: C0415: Import outside toplevel (src.app.lambda_handler) (import-outside-toplevel)
mock_test.py:6:0: W0611: Unused datetime imported from datetime (unused-import)
mock_test.py:9:0: W0611: Unused uuid4 imported from uuid (unused-import)
mock_test.py:12:0: W0611: Unused Session imported from boto3 (unused-import)

2023-04-22 10:23 UTC, meetreks commented on python-test-samples/README.md
Yes, you are correct. Restored the latest one from main and added my new project details.

2023-04-22 10:25 UTC, meetreks commented on python-test-samples/kinesis-lambda-dynamodb/README.md
> +  - [test_kinesis.py](tests/integration/kinesis.py) - Integration tests on a live stack
Corrected the broken link.

2023-04-22 10:26 UTC, meetreks commented on python-test-samples/kinesis-lambda-dynamodb/README.md
> +The SUT is a streaming data processing system. A Lambda function has an Event Source Mapping to a Kinesis Data Stream. The Lambda Event Source Mapping(ESM) polls the Kinesis Data Stream and then sync
Done as requested.

2023-04-22 10:26 UTC, meetreks commented on python-test-samples/kinesis-lambda-dynamodb/README.md
> +The goal of this example is to show how to test Lambda functions that are part of a streaming data processing application. In streaming workloads the number of messages that are sent to Lambda in a b
Done

2023-04-22 10:27 UTC, meetreks commented on python-test-samples/kinesis-lambda-dynamodb/README.md
> +[mock_test.py](src/tests/unit/mock_test.py)
corrected

2023-04-22 10:28 UTC, meetreks commented on python-test-samples/kinesis-lambda-dynamodb/README.md
> +In the [unit test](src/tests/unit/test-handler.test.ts#L44), all references and calls to the DynamoDB service are mocked using aws-sdk-client-mock client.
Removed the line reference and made it general.

2023-04-22 10:35 UTC, meetreks commented on python-test-samples/kinesis-lambda-dynamodb/README.md
> +kinesis-lambda-dynamodb$ pip3 install -r tests/requirements.txt
Added to use a pip parameter --use-pep517 when installing the package.

2023-04-22 10:40 UTC, meetreks commented on python-test-samples/kinesis-lambda-dynamodb/README.md
> +kinesis-lambda-dynamodb$ python3 -m pytest -s tests/unit  -v
Hi I am running Pytest and it passes the tests. I am not sure why the tests are failing in your environment?

2023-04-22 10:49 UTC, meetreks commented on python-test-samples/kinesis-lambda-dynamodb/img/diagram.png
revamped it to match the TypeScript example

2023-04-22 10:50 UTC, meetreks commented on python-test-samples/kinesis-lambda-dynamodb/img/system-under-test-description.png
Kept it in sync with the typescript examples.

2023-04-22 10:51 UTC, meetreks commented on python-test-samples/kinesis-lambda-dynamodb/img/system-under-test.png
Kept it in sync with Type script example.

2023-04-22 10:55 UTC, meetreks commented on python-test-samples/kinesis-lambda-dynamodb/tests/unit/mock_test.py
> +        #check the mocked DynamoDB to see if PK matches to what we passed to the Kinesss Event
Done

2023-04-22 10:57 UTC, meetreks commented on python-test-samples/kinesis-lambda-dynamodb/README.md
> +[test_kinesis.py](tests/integration/test_api_gateway.py)
Fixed

2023-04-22 10:58 UTC, meetreks commented on python-test-samples/kinesis-lambda-dynamodb/img/integration-test-description.png
Used the same images in the Typescript example to keep it in sync.

2023-04-22 18:52 UTC, meetreks commented on python-test-samples/kinesis-lambda-dynamodb/src/app.py
Fixed linting issues

2023-04-22 18:55 UTC, meetreks commented on python-test-samples/kinesis-lambda-dynamodb/tests/unit/mock_test.py
Fixed

2023-04-22 18:56 UTC, meetreks commented on python-test-samples/kinesis-lambda-dynamodb/tests/integration/test_kinesis.py
Fixed

2023-04-22 21:19 UTC, meetreks commented on python-test-samples/kinesis-lambda-dynamodb/README.md
> +kinesis-lambda-dynamodb$ python3 -m pytest -s tests/unit  -v
![image](https://user-images.githubusercontent.com/12427542/233807032-834873c0-fa4e-42fa-b74d-780039624810.png)

2023-04-22 22:46 UTC, meetreks commented on python-test-samples/kinesis-lambda-dynamodb/src/app.py
> +            batch.put_item(Item=item)
Kept it in sync with the Typescript Example

2023-05-02 14:44 UTC, wtromano-aws reviewed
Integration tests are failing, see comment on template.yaml for issue.

2023-05-17 21:19 UTC, wtromano-aws commented
Code verified as functional and comments resolved.  Thank you so much for all the efforts, this will be a very helpful pattern!

2023-05-17 21:19 UTC, wtromano-aws approved these changes

2023-05-17 21:20 UTC, merged