Feature/kinesis lambda dynamodb
aws-samples/serverless-test-samples pull request #109
Opened 2023-04-11 08:29 UTC by rvidis

Kinesis Lambda DynamoDB streaming test scenario fot Typescript

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2023-04-15 14:21 UTC, brnkrygs commented on typescript-test-samples/kinesis-lambda-dynamodb/README.md
> +The Amazon Kinesis Data Stream can stream and data but the AWS Lambda function in this example expects Kinesis Stream Event data to contain a JSON object with 2 properties, `batch` and `id`:
Slight typo?

>can stream "and" data but

2023-04-15 14:22 UTC, brnkrygs commented on typescript-test-samples/kinesis-lambda-dynamodb/README.md
> + - `id`: unique identifier for each individual record. Each records should have a unique `id` property value
Slight typo?

>Each "records" should have

2023-04-15 14:31 UTC, brnkrygs commented on typescript-test-samples/kinesis-lambda-dynamodb/metadata.json
> +          "filepath": "/tests/unit/test-handler.test.ts"
filepath should be: `/src/tests/unit/test-handler.test.ts` I think?

2023-04-15 14:32 UTC, brnkrygs commented on typescript-test-samples/kinesis-lambda-dynamodb/metadata.json
> +          "filepath": "/tests/integration/integ-handler.test.ts"
filepath should be: `/src/tests/integration/integ-handler.test.ts` I think?

2023-04-15 14:35 UTC, brnkrygs commented on typescript-test-samples/kinesis-lambda-dynamodb/src/events/batch-of-five-event.ts
Would prefer this to be a `*.json` file to match other projects.

2023-04-15 14:42 UTC, brnkrygs requested changes
Hi @rvidis, thanks for your work on this sample!

The code all worked from what I've been able to tell. I pulled your branch and ran through the README following your instructions and I got passes for all tests. No build errors. There was even a helpful error message when I forgot to set my stack environment variable. Nice job!

I added some inline comments to a couple of files with typos, and found where you might want to update the sample metadata. As soon as those are fixed I think we can merge.

I'd love to see a followup to this that tested some of the Kinesis error handling logic - how partial batch failure behaves, etc. but I don't want to hold this up waiting for that.

2023-04-16 07:38 UTC, rvidis commented
Thank you for the review @brnkrygs, I have addressed all comments.

2023-04-16 17:12 UTC, brnkrygs commented on typescript-test-samples/kinesis-lambda-dynamodb/metadata.json
> +        "name": "Debasis Mitra",
@rvidis one small tweak yet - wrong name is here.

Want to make sure you get credit! :)

2023-04-16 17:13 UTC, brnkrygs requested changes
One small change needed yet: your name on the `metadata.json` file :) then we can GTM

2023-04-16 21:45 UTC, brnkrygs approved these changes
Looks good! Merging.

2023-04-16 21:45 UTC, merged