fixing links to files for metadata
aws-samples/serverless-test-samples pull request #169
Opened 2023-04-18 09:15 UTC by boyney123

Fix for a few files that have broken links to files.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2023-04-18 10:14 UTC, boyney123 commented on dotnet-test-samples/apigw-lambda-list-s3-buckets/metadata.json
> +    "type": ["Integration"],
From what I understand the pattern is only showing an integration test?

```
 "pattern_detail_tabs": [
        {
            "title": "Application Code",
            "filepath": "/src/ServerlessTestSamples/Function.cs"
        },
        {
            "title": "Integration Test",
            "filepath": "/tests/ServerlessTestSamples.IntegrationTest/IntegrationTest.cs"
        }        
    ],
 ```
 
 Others have unit + integration in the array, so I thought I would remove the tag for Unit, as I can't see one?

2023-04-18 11:08 UTC, dhelper commented on dotnet-test-samples/apigw-lambda-list-s3-buckets/metadata.json
> +    "type": ["Integration"],
We have both, I guess I accidently did not add the unit test folder (test/ServerlessTestSamples.UnitTest

2023-04-28 12:22 UTC, brnkrygs commented
TypeScript changes look good. Though, I'm a bit thrown because from what I can see, `main` already has fixed links for that sample:

https://github.com/aws-samples/serverless-test-samples/blob/main/typescript-test-samples/apigw-lambda-dynamodb/metadata.json

2023-04-28 13:32 UTC, wtromano-aws requested changes
I think some of the linking issues may already be resolved in a recent merge, as I am seeing redundant changes.  Perhaps fast-forward to the changes already in main?

2023-04-28 13:32 UTC, wtromano-aws commented on dotnet-test-samples/apigw-lambda-list-s3-buckets/metadata.json
> +    "type": ["Integration"],
Thank you, good find here, let's move forward with just "integration" for this MR, and we can follow up with a separate MR to add the unit tests to this patter.

2023-04-28 13:32 UTC, wtromano-aws commented on dotnet-test-samples/apigw-lambda-list-s3-buckets/metadata.json
> +            "filepath": "/src/ServerlessTestSamples/Function.cs"
Should have multiple - array of {title, filepath}  to the key Application code and test code.

2023-04-28 13:32 UTC, wtromano-aws commented on python-test-samples/lambda-mock/metadata.json
This change is already in the main branch

2024-06-06 14:47 UTC, brnkrygs commented
Closing as abandoned. Repo structure has evolved since this was opened.

2024-06-06 14:47 UTC, closed without merging