Resolves Issue 110
aws-samples/serverless-test-samples pull request #188
Opened 2023-04-24 02:29 UTC by arthi-j

*Issue #, if available:* https://github.com/aws-samples/serverless-test-samples/issues/110

*Description of changes:* Python sample code for schema and contract testing

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2023-04-24 19:25 UTC, wtromano-aws requested changes
Great pattern, thank you so much for contributing!  It looks great as-is, but I have some minor formatting and cosmetic improvement comments that are very minor in scope.  Certainly let me know of any questions on the feedback.

2023-04-24 19:25 UTC, wtromano-aws commented on python-test-samples/schema-and-contract-testing/tests/test_schema.py
Pylint:

test_schema.py:27:0: C0301: Line too long (107/100) (line-too-long)
test_schema.py:53:0: C0301: Line too long (126/100) (line-too-long)
test_schema.py:1:0: C0114: Missing module docstring (missing-module-docstring)
test_schema.py:5:0: E0401: Unable to import 'pytest' (import-error)
test_schema.py:7:0: E0401: Unable to import 'pydantic' (import-error)
test_schema.py:15:0: C0116: Missing function or method docstring (missing-function-docstring)
test_schema.py:17:9: W1514: Using open without explicitly specifying an encoding (unspecified-encoding)
test_schema.py:17:41: C0103: Variable name "f" doesn't conform to snake_case naming style (invalid-name)
test_schema.py:24:0: C0116: Missing function or method docstring (missing-function-docstring)
test_schema.py:31:0: C0116: Missing function or method docstring (missing-function-docstring)
test_schema.py:38:0: C0116: Missing function or method docstring (missing-function-docstring)
test_schema.py:40:8: W0612: Unused variable 'customer' (unused-variable)
test_schema.py:51:0: C0116: Missing function or method docstring (missing-function-docstring)
test_schema.py:7:0: C0411: third party import "from pydantic import ValidationError" should be placed before "from tests.context import CustomerModel" (wrong-import-order)

2023-04-24 19:25 UTC, wtromano-aws commented on python-test-samples/schema-and-contract-testing/tests/test_contract.py
Pylint:

test_contract.py:19:0: C0301: Line too long (107/100) (line-too-long)
test_contract.py:1:0: C0114: Missing module docstring (missing-module-docstring)
test_contract.py:2:0: E0401: Unable to import 'pytest' (import-error)
test_contract.py:4:0: E0401: Unable to import 'pydantic' (import-error)
test_contract.py:8:0: C0116: Missing function or method docstring (missing-function-docstring)
test_contract.py:10:9: W1514: Using open without explicitly specifying an encoding (unspecified-encoding)
test_contract.py:10:41: C0103: Variable name "f" doesn't conform to snake_case naming style (invalid-name)
test_contract.py:17:0: C0116: Missing function or method docstring (missing-function-docstring)
test_contract.py:24:0: C0116: Missing function or method docstring (missing-function-docstring)
test_contract.py:26:8: W0612: Unused variable 'customer' (unused-variable)
test_contract.py:4:0: C0411: third party import "from pydantic import ValidationError" should be placed before "from tests.context import ConsumerCustomerModel" (wrong-import-order)

2023-04-24 19:25 UTC, wtromano-aws commented on python-test-samples/schema-and-contract-testing/tests/context.py
Pylint:

context.py:1:0: C0114: Missing module docstring (missing-module-docstring)
context.py:16:0: E0401: Unable to import 'customer_v1_0_0_with_validation' (import-error)
context.py:16:0: C0413: Import "from customer_v1_0_0_with_validation import Customer as ConsumerCustomerModel" should be placed at the top of the module (wrong-import-position)
context.py:17:0: E0401: Unable to import 'customer_v1_0_0' (import-error)
context.py:17:0: C0413: Import "from customer_v1_0_0 import Customer as CustomerModel" should be placed at the top of the module (wrong-import-position)
context.py:16:0: W0611: Unused Customer imported from customer_v1_0_0_with_validation as ConsumerCustomerModel (unused-import)

2023-04-24 19:25 UTC, wtromano-aws commented on python-test-samples/schema-and-contract-testing/src/customer_v1_0_0_with_validation.py
Pylint:

customer_v1_0_0.py:1:0: C0114: Missing module docstring (missing-module-docstring)
customer_v1_0_0.py:9:0: C0115: Missing class docstring (missing-class-docstring)
customer_v1_0_0.py:9:0: R0903: Too few public methods (0/2) (too-few-public-methods)

2023-04-24 19:25 UTC, wtromano-aws commented on python-test-samples/schema-and-contract-testing/src/customer_v1_1_0.py
Pylint:

customer_v1_2_0.py:1:0: C0114: Missing module docstring (missing-module-docstring)
customer_v1_2_0.py:8:0: E0401: Unable to import 'pydantic' (import-error)
customer_v1_2_0.py:11:0: C0115: Missing class docstring (missing-class-docstring)
customer_v1_2_0.py:11:0: R0903: Too few public methods (0/2) (too-few-public-methods)

2023-04-24 19:25 UTC, wtromano-aws commented on python-test-samples/schema-and-contract-testing/src/customer_v1_2_0.py
customer_v1_2_0.py:1:0: C0114: Missing module docstring (missing-module-docstring)
customer_v1_2_0.py:8:0: E0401: Unable to import 'pydantic' (import-error)
customer_v1_2_0.py:11:0: C0115: Missing class docstring (missing-class-docstring)
customer_v1_2_0.py:11:0: R0903: Too few public methods (0/2) (too-few-public-methods)

2023-04-24 19:25 UTC, wtromano-aws commented on python-test-samples/schema-and-contract-testing/src/customer_v1_3_0.py
Pylint:

customer_v1_3_0.py:1:0: C0114: Missing module docstring (missing-module-docstring)
customer_v1_3_0.py:8:0: E0401: Unable to import 'pydantic' (import-error)
customer_v1_3_0.py:11:0: C0115: Missing class docstring (missing-class-docstring)
customer_v1_3_0.py:11:0: R0903: Too few public methods (0/2) (too-few-public-methods)

2023-04-24 19:25 UTC, wtromano-aws commented on python-test-samples/schema-and-contract-testing/src/customer_v1_4_0.py
Pylint (Although the last error is probably intentional and can be ignored)

customer_v1_4_0.py:1:0: C0114: Missing module docstring (missing-module-docstring)
customer_v1_4_0.py:8:0: E0401: Unable to import 'pydantic' (import-error)
customer_v1_4_0.py:11:0: C0115: Missing class docstring (missing-class-docstring)
customer_v1_4_0.py:11:0: R0903: Too few public methods (0/2) (too-few-public-methods)
customer_v1_4_0.py:1:0: R0801: Similar lines in 2 files
==src.customer_v1_0_0:[8:17]
==src.customer_v1_0_0_with_validation:[8:20]

2023-04-28 05:06 UTC, arthi-j commented on python-test-samples/schema-and-contract-testing/README.md
Done

2023-04-28 05:06 UTC, arthi-j commented on python-test-samples/schema-and-contract-testing/README.md
> +
Done

2023-04-28 05:06 UTC, arthi-j commented on python-test-samples/schema-and-contract-testing/README.md
> +    - [Goal](#goal)
Done

2023-04-28 05:07 UTC, arthi-j commented on python-test-samples/schema-and-contract-testing/README.md
> +This test is integration service agnostic, as it runs against the schema published to a schema registry. Amazon EventBridge Schema Registry is one example of such a registry. It provides schemas for
Done

2023-04-28 05:07 UTC, arthi-j commented on python-test-samples/schema-and-contract-testing/tests/test_schema.py
> +# parameter
Done

2023-04-28 05:07 UTC, arthi-j commented on python-test-samples/schema-and-contract-testing/src/customer_v1_4_0.py
Not all Pylint recommendations make sense. Updated where relevant.

2023-04-28 13:04 UTC, wtromano-aws approved these changes

2023-04-28 13:04 UTC, merged