Readme updates
aws-samples/serverless-test-samples pull request #23
Opened 2022-11-08 14:45 UTC by rohanmeh

*Issue #, if available:*

*Description of changes:*
Add intro links, gif, move testing guidance "theory" to separate file, add async test sample list.

Note: Typescript and Java links need to be updated after the PR's for those samples are merged into main.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2022-11-14 19:01 UTC, dancfox requested changes

2022-11-14 19:28 UTC, dancfox commented
I'm conflicted about the "moving test theory into a different file" but am willing to merge it for now and see how it feels.

2022-11-16 05:13 UTC, rohanmeh commented on README.md
> +<div align="center">
The example "good" Readme's use center alignment but it's not a must have for me - would be fine left aligned as well.

There's no way to do center-aligned markdown text without the html (from what i see on stackoverflow)

I agree we can be consistent about not using HTML unless we absolutely have to.

2022-11-16 05:14 UTC, rohanmeh commented on README.md
> +<a href="https://github.com/aws-samples/serverless-test-samples/tree/main/python-test-samples">Typescript</a>
I think Java should be ready in the next few days so I can update the link in the PR and then we can merge it in?

Will update the PR with Typescript link.

2022-11-16 05:15 UTC, rohanmeh commented on README.md
> +<a href="https://github.com/aws-samples/serverless-test-samples/tree/main/python-test-samples">Typescript</a>
I think we can "launch" the repo with all 3 sample folders (Python Typescript Java) and the updated readme all together.

2022-11-16 05:17 UTC, rohanmeh commented
> 

About test theory in separate file, what I saw in other readme's was they didn't have large blocks of texts like we did - they got straight to the point. I think that content will mostly live in ServerlessLand (and other docs pages) in the future, but willing to put it back in if we need to.

2022-12-06 21:13 UTC, dancfox approved these changes

2022-12-06 21:14 UTC, merged